### ISSUE TITLE
VimFx works oddly in slowly-loading pages

### ISSUE THREAD

**Issue by darvelo** [akhodakivskiy/VimFx#588]
I've bound Previous/Next Tab to `J` and `K` (but also tested mapping `E` and `e`). I like to hold `Shift` and hold or rapidly press `j` or `k` rather than using counts with `gt/gT`. The issue is that if I rapidly switch, let's say, 5 or more tabs behind/ahead, the expected behavior occurs for the first few tabs but then seems to "get stuck", where the UI appears to stay on a tab when it really should have already switched many more tabs behind/ahead. In reality Firefox *has* switched to as many tabs as the hotkey was pressed, but the UI isn't rerendered (or something). I know this because even though it looks like it got stuck, if I press any key (even just `Shift` by itself), the UI rerenders and I'm on the tab I expected to be on. This bug doesn't seem to happen consistently.

VimFx: 0.6.1
Firefox: 42 and Developer Edition, e10s multi-process disabled
OS: Linux
Keyboard Layout: US English

**Comment by lydell** [comment]
I just tried the following with the same setup as you:

1. Opened 14 tabs.
2. Held down shift.
3. Spammed `J` as fast as I could. Spammed `K` as fast as I could. Held `J` for several seconds. Held `K` for several seconds. Alternated between `J` and `K` randomly.

I noticed no UI re-render problems at all.

**Comment by alectic** [comment]
I have the same problem, only that I've noticed it in a slightly different way. I use the "BarTab Heavy" extension and have it set to not load the links when I open them in new tabs. So very often I open a new link in a background tab using VimFx and then quickly switch to it pressing "gt" then press ctrl-l and enter to load the url, then quickly "gT" to go back to the previous tab. But instead of going back to the previous tab, it seems as if VimFx is frozen and doesn't respond to my commands, sometimes for one sec sometimes for a little longer than that, and if I press "gT" again it will either switch two tabs back but with a delay or don't switch at all for the moment and only switch when I press again a VimFx shortcut like j even if that's 5 seconds later. It seems that's starting to happen when a tab is loading, or that's when i've experiened it so far.

VimFx: 0.6.0
Firefox: 42.0
OS: Arch Linux x64

**Comment by lydell** [comment]
@alectic I’m not sure if your problem is the same, but thanks for reporting it! I think I’ve fixed your issue.

**Comment by alectic** [comment]
@lydell It seemed to be the same thing @darvelo experienced with tabs. Thanks for the fix, I'll report back to confirm when I have a chance.

**Comment by lydell** [comment]
@darvelo @alectic Would you mind checking if your issues occur in VimFx 0.6.2 as well?

**Comment by darvelo** [comment]
@lydell Yes, unfortunately it still occurs for me. I think @alectic is right that it has something to do with unloaded tabs. I have the "Don't load tabs until selected" setting turned on in Firefox preferences because I always have >200 tabs open in a session. This issue seems to occur after loading previously-not-loaded tabs either by clicking them with the mouse or using the VimFx previous/next hotkeys.

**Comment by lydell** [comment]
Thanks for your detailed instructions! :+1: Still having a hard time reproducing, though…

**Comment by darvelo** [comment]
I think I've isolated the problem. I disabled all my plugins except for VimFx. It only occurs when NoScript is also enabled. All my other plugins play nicely. :smile:

**Comment by alectic** [comment]
@lydell I have the "Don't load tabs until selected" option enabled as well for the same reason @darvelo mentioned, but I never suspected that to be the cause of my issue, and It seems to be fixed for me. I tried hard to reproduce it and it appeares to be gone in my case. I also use noscript but that never seemed to cause any problems with vimfx, I don't see why it would.

I tried @darvelo's instructions and besides the normal slowness of the browser when loading multiple tabs at the same time, I'm not experiencing the same thing.

**Comment by lydell** [comment]
Thanks for your updates guys!

**Comment by BohrShaw** [comment]
I also encounter this issue from time to time, i.e. the tab is not switched until a key like `Shift` is pressed.
This happens especially on a slowly-loading page, regardless of the number of tabs.

I have no NoScript installed.
System info: `VimFx 0.7.3 on Firefox 42(or Firefox Dev) on Windows 10`

**Comment by lydell** [comment]
I have a _theory_ on what happens. This _might_ be because of commit f856db46867305ec34fab89e1d6fc956dacb37af. I’m thinking that since JavaScript is single-threaded, that `utils.nextTick` won’t happen until something else slow and blocking is done when loading the page.

It would be awesome if people who can reproduce the bug could try it out in multi-process as well and see if it happens there. Extra bonus points if you remove the `utils.nextTick` wrapper for the `J` and `K` commands and try that too.

**Comment by lydell** [comment]
I’ve made a version of VimFx with `utils.nextTick` for `J` and `K` removed. That will cause other problems (only in non-multi-process), but will hopefully tell if this is the cause of this particular issue.

[VimFx.txt](https://github.com/akhodakivskiy/VimFx/files/52449/VimFx.txt)

1. Download the above file
2. Rename it to VimFx.xpi
3. Install it in Firefox

**Comment by just-barcodes** [comment]
I can reproduce the bug in both single and multi-process firefox with both VixFx 0.9.0 and the new version you posted here.
OS: Linux
NoScript installed
`Dont load tabs until selected` option activated

I think one way to reproduce the bug is to load lots of pages and then rapidly switch between them with `J` or `K` before they have finished loading (e.g. restart firefox with lots of open tabs and  `Show my windows and tabs from last time` option)

**Comment by just-barcodes** [comment]
Oh, by the way it not only happens with `J` and `K` but also sometimes when closing a tab with `x`

**Comment by korakinos** [comment]
Same issue here. It also happens with `t`(new tab).

If not everybode can reproduce this bug, maybe it only occurs when Firefox has a certain amount of lag (on key entry) anyway, so depending on the system/computer? On my system, typing in Firefox's address field is always noticeably delayed, with or without VimFX. This is just a wild guess, though.

**Comment by BohrShaw** [comment]
I actually constantly encounter this issue; probably due to my bad network, e.g. when it's stuck in "transferring data from ...".

**Comment by darvelo** [comment]
FWIW, in Firefox Developer Edition they removed Tab Groups, and since then I haven't noticed this issue. If I notice it again I'll report back to confirm. Firefox version 45, with this update, gets released in a couple months, I think.

**Comment by BohrShaw** [comment]
For me, Firefox Dev Edition (version 45) is no exception.

**Comment by lydell** [comment]
It'd be really helpful if somebody could try the following experiment:

1. Install [Node.js](http://nodejs.org/).
2. Paste the code at the bottom of this post in a file called index.js.
3. Run `node index.js`.
4. Visit http://localhost:8000/ in Firefox.
5. See if you can reproduce the problem while loading that page. (It should take
   about 20 seconds to load.)

```js
var http = require('http')

var server = http.createServer(function(req, res) {
  console.log('Responding to request')
  res.write('Counting down...\n')
  slowlyCountdown(res, 10)
})

server.listen(8000)
console.log('Server listening at http://localhost:8000/')

function slowlyCountdown(res, i) {
  setTimeout(function() {
    res.write(i + '\n')
    if (i <= 0) {
      res.end('done!')
      console.log('Done responding to request')
    } else {
      slowlyCountdown(res, i - 1)
    }
  }, 2000)
}
```

**Comment by BohrShaw** [comment]
I've just tried this snippet and it doesn't reproduce the problem. (Switching tabs from that page is instant.)

**Comment by just-barcodes** [comment]
I also just tried and couldn't reproduce the problem.

**Comment by lydell** [comment]
Let's summarize what we know about this issue. I'm starting to get a bit confused.

When _some_ (?) pages load (slowly) it feels as if _some_ (ones that results in another tab being selected, such as `J`, `K`, `x`, `X`, `t`, `yt`? Do other commands work at this time, such as `o`?) commands don't do anything, until you press _some_ key (shift has been mentioned; does any other keys also cut it?). What happens if you _don't_ press for example shift? Does the UI never update?

A video/gif/series of screenshots would be helpful, too.

**Comment by BohrShaw** [comment]
> Do other commands work at this time, such as o?

No.

> does any other keys also cut it?
> What happens if you don't press for example shift? Does the UI never update?

Yes for both.

**Comment by BohrShaw** [comment]
> does any other keys also cut it?

To be more specific:

1. Press `gt` on a slowly-loading page. It doesn't respond.
1. After the page is loaded, Press `j` would switch to the next tab and execute `j` on that tab.

**Comment by lydell** [comment]
Ok, what about this then?

1. Press `gt` on a slowly-loading page.
2. After the page is loaded:

   - What does the Firefox built-in shortcut `<c-w>` do? (It's supposed to close the current tab.)
   - What happens if you try to scroll or click something using the mouse?

**Comment by BohrShaw** [comment]
`<c-w>` always closes the current tab; actually, native shortcuts like `<m-d>` and mouse click work as expected.

**Comment by Joe5** [comment]
I think I have the same problem. Here is what I did notice that could be of some help:

1. Load some page which has longer loading time or just try it on older hardware/slower internet connection.
2. During loading time fire some VimFx command for example switching tab J/K.
3. Everything will "hang" and after the tab is loaded the command will run.
4. I can switch tab manually using mouse or ctrl+tab without any problems.

One more thing I have noticed. VimFx is not responding to my commands when I have opened firebug addon (browser dev tools) and I am focused in its panel. It started around the same time this bug was introduced and was working correctly before.

Its quite annoying and happens frequently. I've been using your plugin for a few months now and in the past I never noticed this problem. I think that all started after releasing that big release later this year and when "f" command got a speed boost.

**Comment by lydell** [comment]
@BohrShaw Does it matter if multi-process is enabled?

**Comment by BohrShaw** [comment]
I can't know now as these days I'm on Chrome and this bug is not always reproducible.

**Comment by lydell** [comment]
@darvelo, @just-barcodes, @Joe5, @BohrShaw, @korakinos I just pushed a commit that is supposed to make VimFx's keyboard shortcuts handling more robust and responsive. Could you please try out the latest master and see if that works better?

**Comment by just-barcodes** [comment]
I could reproduce the 'not switching tab' behavior at least once with the latest master version. Can't yet say if it happens less often or not.

**Comment by lydell** [comment]
- Is there a specific website where this is easier to reproduce?
- What is a “bad connection”?

**Comment by korakinos** [comment]
I was on a very slow internet connection for a few days (like dialup, slow ping and slow throughput), and I was able to reproduce the bug with various webpages. Pages with many pictures worked best, e.g. news sites like http://www.tagesschau.de/ .

Unfortunately, while on the slow connection, I couldn't install the build requirements for VimFX to test the latest git version. Now that the connection is back to normal, I am having trouble finding a slow enough page again...

**Comment by Joe5** [comment]
Yes I think I could try latest master but I don't know how. Is there some kind of a release or do I have to build it from source?

About the slow connection. I think there should be a software that allows you to slow your internet connection to what ever you like, even dial up. It was used to test new websites while in development. Unfortunately I have never used such software so I cannot recommend such program.

**Comment by lydell** [comment]
@Joe5 https://github.com/akhodakivskiy/VimFx/blob/master/documentation/tools.md

**Comment by korakinos** [comment]
With VimFx from git I haven't been able to reproduce the bug in the last two days. Moreover, after reinstalling the VimFx release from addons.mozilla.org, I could reproduce it instantly on a slowly-loading twitter page. So, from my view, the bug seems to be fixed.

**Comment by just-barcodes** [comment]
So in the last 12 days in which I used the master-branch version, I had the bug happen to me maybe 2 or 3 times, which is a lot less then before. It is probably also connected to my often heavily loaded system, on which the whole browser is sometimes very slow.

**Comment by Joe5** [comment]
I think it is better but its not that easy to say since it's not something that happens every time I push a button.

**Comment by lydell** [comment]
If there’s anyone who’d like to test this but didn’t want to build VimFx yourself, you may now try the changes out in VimFx 0.11.0.

I recently started to use NoScript, and since then I sometimes notice that nothing appears to happen when I press `J` and `K`. Pressing some other key before or after makes the tab switch actually happen. So @darvelo’s original issue might actually be about NoScript, but since then this issue has taken a new direction. So please test _without_ NoScript. We’ll come back to that some other time.

**Comment by lydell** [comment]
Regarding NoScript, today I noticed this in the error console  when I experienced the problem:

```
[NoScript ClearClick] Swallowed event keydown on http://www.tab1.com/ (rapid fire from https://www.tab2.com in 512ms)
[NoScript ClearClick] Swallowed event keyup on http://www.tab1.com/ (rapid fire from https://www.tab2.com in 592ms)
```

**Comment by lydell** [comment]
An update on NoScript: I managed to track down the problem a little closer, and I think it is a minor bug in NoScript. I’ve posted an issue about it here: https://forums.informaction.com/viewtopic.php?f=10&t=21597

**Comment by darvelo** [comment]
@lydell Amazing detective work. Though I'm not affected by the issue as I'm on multi-process now, hopefully the NoScript developer(s) can solve it.

**Comment by Joe5** [comment]
I am not using NoScript but since the update it's much better than it use to be.
